# Generated by Django 4.2 on 2024-12-28 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_app_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='app_password',
        ),
    ]
