# Generated by Django 4.2 on 2024-10-23 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications_manager', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_layout', models.TextField(verbose_name='Сообщение')),
                ('header', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, которому принадлежит сообщение')),
            ],
        ),
        migrations.AlterField(
            model_name='recipient_contact',
            name='contact',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта получателя'),
        ),
        migrations.AlterField(
            model_name='recipient_contact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, которому принадлежит список рассылки'),
        ),
        migrations.DeleteModel(
            name='Current_contact_type',
        ),
    ]
