# Generated by Django 4.2 on 2024-12-28 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_app_password'),
        ('notifications_manager', '0003_message_alter_recipient_contact_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmtpLoginAndServerData',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email', models.EmailField(max_length=254)),
                ('app_password', models.CharField(max_length=50)),
                ('is_mail_server_configured', models.BooleanField(default=False)),
                ('mail_server_host', models.CharField(blank=True, max_length=70, null=True)),
                ('mail_server_port', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
