# Generated by Django 4.2 on 2024-12-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
