# Generated by Django 4.2 on 2025-01-14 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_remove_user_app_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmtpCredentials',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, которому принадлежит строка данных с данными smtp')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта пользователя. Она дублирует ту, что в модели User')),
                ('smtp_password', models.CharField(max_length=50, verbose_name='Пароль с помощью которого будет осуществляться вход на smtp сервер')),
                ('smtp_server_host', models.CharField(blank=True, max_length=70, null=True, verbose_name='Хост smtp сервера')),
                ('smtp_server_port', models.CharField(blank=True, max_length=5, null=True, verbose_name='Порт smtp сервера')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('subject', models.CharField(max_length=150, verbose_name='Тема сообщения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, которому принадлежит сообщение')),
            ],
        ),
        migrations.CreateModel(
            name='RecipientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.EmailField(max_length=254, verbose_name='Электронная почта получателя')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, которому принадлежит список рассылки')),
            ],
            options={
                'unique_together': {('contact', 'user')},
            },
        ),
    ]
